platform :ios, '9.0'

target 'Pelican' do

  use_frameworks!

  pod 'Pelican', :path => '..'
  
  target 'PelicanTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
